name: pr-title-check
permissions:
  pull-requests: read
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce Conventional Commit style in PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
